export const airports = [
    { value: "北京首都國際機場 (PEK)", label: "北京首都國際機場 (PEK)" },
    { value: "上海浦東國際機場 (PVG)", label: "上海浦東國際機場 (PVG)" },
    { value: "東京羽田機場 (HND)", label: "東京羽田機場 (HND)" },
    { value: "首爾仁川國際機場 (ICN)", label: "首爾仁川國際機場 (ICN)" },
    { value: "新加坡樟宜機場 (SIN)", label: "新加坡樟宜機場 (SIN)" },
    { value: "曼谷素萬那普國際機場 (BKK)", label: "曼谷素萬那普國際機場 (BKK)" },
    { value: "吉隆坡國際機場 (KUL)", label: "吉隆坡國際機場 (KUL)" },
    { value: "德里英迪拉·甘地國際機場 (DEL)", label: "德里英迪拉·甘地國際機場 (DEL)" },
    { value: "馬尼拉尼諾伊·阿基諾國際機場 (MNL)", label: "馬尼拉尼諾伊·阿基諾國際機場 (MNL)" },
    { value: "雅加達蘇加諾-哈達國際機場 (CGK)", label: "雅加達蘇加諾-哈達國際機場 (CGK)" },
    { value: "香港國際機場 (HKG)", label: "香港國際機場 (HKG)" },
    { value: "台北桃園國際機場 (TPE)", label: "台北桃園國際機場 (TPE)" },
    { value: "高雄國際機場 (KHH)", label: "高雄國際機場 (KHH)" },
    { value: "東京成田國際機場 (NRT)", label: "東京成田國際機場 (NRT)" },
    { value: "大阪關西國際機場 (KIX)", label: "大阪關西國際機場 (KIX)" },
    { value: "札幌新千歲機場 (CTS)", label: "札幌新千歲機場 (CTS)" },
    { value: "福岡機場 (FUK)", label: "福岡機場 (FUK)" },
    { value: "沖繩那霸機場 (OKA)", label: "沖繩那霸機場 (OKA)" },
    { value: "廣州白雲國際機場 (CAN)", label: "廣州白雲國際機場 (CAN)" },
    { value: "深圳寶安國際機場 (SZX)", label: "深圳寶安國際機場 (SZX)" },
    { value: "西安咸陽國際機場 (XIY)", label: "西安咸陽國際機場 (XIY)" },
    { value: "成都雙流國際機場 (CTU)", label: "成都雙流國際機場 (CTU)" },
    { value: "重慶江北國際機場 (CKG)", label: "重慶江北國際機場 (CKG)" },
    { value: "悉尼金斯福德·史密斯機場 (SYD)", label: "悉尼金斯福德·史密斯機場 (SYD)" },
    { value: "墨爾本圖拉馬林機場 (MEL)", label: "墨爾本圖拉馬林機場 (MEL)" },
    { value: "布里斯班機場 (BNE)", label: "布里斯班機場 (BNE)" },
    { value: "珀斯機場 (PER)", label: "珀斯機場 (PER)" },
    { value: "奧克蘭國際機場 (AKL)", label: "奧克蘭國際機場 (AKL)" },
    { value: "威靈頓國際機場 (WLG)", label: "威靈頓國際機場 (WLG)" },
    { value: "基督城國際機場 (CHC)", label: "基督城國際機場 (CHC)" },
  ];
  